# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67e2bb45d510f94f4278d73e43edd1352c9ca11e487f5b009cffeff8fc2c9b3f16b94fddd5ea59ebce812449d305660abb5272a858d282770267300a5bd45c91

test:
  secret_key_base: 5e486d4192c1ed3ff3be8d14352654a199dfb34a019f669094f7cb0618a4810eab23b6c721aabddf34fa7d4c2d45e692bb7a646564accd6915f67f32569e43a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
