# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1de7dc4f41eefe14cddf3c848091d61180d026d6bb908278bbcc473843f6baf164194663aac9b8ef3738338ea37b999cced9cdc813d48fefdf0d998bfcdef23

test:
  secret_key_base: f2fca187c5dbb18cadd85f0091de4570ad7ee09c23ea21b0cd82c4728f83fcf3312e5706ff49872bf8b8c151d56a1d064558b06358b44d2dd7a3b68b18898322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
